apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyummenu
  labels:
    app: TruYumWebApiInAzure
spec:
  replicas: 1
  selector:
    matchLabels:
      service: truyummenu
  template:
    metadata:
      labels:
        app: TruYumWebApiInAzure
        service: truyummenu
    spec:
      containers:
        - name: truyummenu
          image: truyumregistry.azurecr.io/truyummenu:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: truyummenu
  labels:
    app: TruYumWebApiInAzure
    service: truyummenu
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: truyummenu